# Generated by Django 5.1.6 on 2025-03-05 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('sum_value', models.FloatField()),
                ('average_value', models.FloatField()),
                ('count_value', models.IntegerField()),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.csvfile')),
            ],
        ),
    ]
